from django.urls import path
from .views import *
from .query_essential import query_essential_1, query_essential_2, query_essential_3, query_post
from .result import result_f
from .test_essential import test_essential_f

urlpatterns = [
    path('home_page/', home_page),
    path('4000_essential_english_words/', essential_english_words),
    path('error/', error),
    path('settings/', settings),
    path('about/', about),
    path('play_again/', play_again),

    path('api/query_essential/', query_post),
    path('query_essential_1/', query_essential_1),
    path('query_essential_2/', query_essential_2),
    path('query_essential_3/', query_essential_3),

    path('select_essential/', select_essential_page),

    path('test_essential/', test_essential_f),
    path('result/', result_f)
]



"""  <<<<<<<< Keyinchalik o'qishim kerak >>>>>>

Django settings for word project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""